\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename ekg.info
@settitle ekg, the Emacs Knowledge Graph
@documentencoding UTF-8
@documentlanguage en
@set MAINTAINER Andrew Hyatt
@set MAINTAINEREMAIL @email{ahyatt@gmail.com}
@set MAINTAINERCONTACT @uref{mailto:ahyatt@gmail.com,contact the maintainer}
@c %**end of header

@dircategory Emacs
@direntry
* EKG: (ekg).           A note taking application for emacs using sqlite.
@end direntry

@finalout
@titlepage
@title ekg, the Emacs Knowledge Graph
@author Andrew Hyatt (@email{ahyatt@@gmail.com})
@end titlepage

@contents

@ifnottex
@node Top
@top ekg, the Emacs Knowledge Graph

more
@end ifnottex



@bye
