#!/bin/bash
# Copyright (C) 2026  Andrew Hyatt <ahyatt@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# ekg-update-tags - Add or remove tags on an existing note
#
# Usage: ekg-update-tags <note-id> --add tag1 --remove tag2 [--daemon name]

set -e

NOTE_ID=""
ADD_TAGS=()
REMOVE_TAGS=()
DAEMON_NAME=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --add)
            ADD_TAGS+=("$2")
            shift 2
            ;;
        --remove)
            REMOVE_TAGS+=("$2")
            shift 2
            ;;
        --daemon)
            DAEMON_NAME="$2"
            shift 2
            ;;
        --help)
            echo "Usage: ekg-update-tags <note-id> --add tag1 --remove tag2 [--daemon name]"
            echo ""
            echo "Options:"
            echo "  --add TAG       Add a tag (repeatable)"
            echo "  --remove TAG    Remove a tag (repeatable)"
            echo "  --daemon NAME   Emacs daemon name (optional)"
            exit 0
            ;;
        *)
            if [[ -z "$NOTE_ID" ]]; then
                NOTE_ID="$1"
            else
                echo "Error: Unexpected argument: $1"
                exit 1
            fi
            shift
            ;;
    esac
done

if [[ -z "$NOTE_ID" ]]; then
    echo "Error: Note ID is required"
    exit 1
fi

if [[ ${#ADD_TAGS[@]} -eq 0 && ${#REMOVE_TAGS[@]} -eq 0 ]]; then
    echo "Error: At least one --add or --remove is required"
    exit 1
fi

# Build add tags elisp list
ADD_ELISP="("
for tag in "${ADD_TAGS[@]}"; do
    escaped="${tag//\"/\\\"}"
    ADD_ELISP+="\"$escaped\" "
done
ADD_ELISP="${ADD_ELISP% })"

# Build remove tags elisp list
REMOVE_ELISP="("
for tag in "${REMOVE_TAGS[@]}"; do
    escaped="${tag//\"/\\\"}"
    REMOVE_ELISP+="\"$escaped\" "
done
REMOVE_ELISP="${REMOVE_ELISP% })"

ELISP_EXPR="(progn
  (require 'ekg)
  (ekg-connect)
  (let ((note (ekg-get-note-with-id $NOTE_ID)))
    (if note
        (progn
          (dolist (tag '$ADD_ELISP)
            (unless (member tag (ekg-note-tags note))
              (push tag (ekg-note-tags note))))
          (dolist (tag '$REMOVE_ELISP)
            (setf (ekg-note-tags note) (delete tag (ekg-note-tags note))))
          (ekg-save-note note)
          (princ (format \"Updated note $NOTE_ID. Tags: %s\" (ekg-note-tags note))))
      (princ \"Error: Note $NOTE_ID not found\"))))"

EMACSCLIENT_CMD=("${EMACSCLIENT:-emacsclient}")
if [[ -n "$DAEMON_NAME" ]]; then
    EMACSCLIENT_CMD+=("-s" "$DAEMON_NAME")
fi

if ! OUTPUT=$("${EMACSCLIENT_CMD[@]}" --eval "$ELISP_EXPR" 2>&1); then
    echo "Error: Failed to update tags. Is the Emacs daemon running?" >&2
    echo "$OUTPUT" >&2
    exit 1
fi

echo "$OUTPUT" | sed 's/^"//; s/"$//'
