#!/bin/bash
# Copyright (C) 2026  Andrew Hyatt <ahyatt@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# ekg-trash - Trash (soft-delete) a note by ID
#
# Usage: ekg-trash <note-id> [--daemon name]
#
# Moves the note to trash. If already trashed, permanently deletes it.

set -e

NOTE_ID=""
DAEMON_NAME=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --daemon)
            DAEMON_NAME="$2"
            shift 2
            ;;
        --help)
            echo "Usage: ekg-trash <note-id> [--daemon name]"
            echo ""
            echo "Trash a note by its ID. If already trashed, permanently deletes it."
            exit 0
            ;;
        *)
            if [[ -z "$NOTE_ID" ]]; then
                NOTE_ID="$1"
            else
                echo "Error: Unexpected argument: $1"
                exit 1
            fi
            shift
            ;;
    esac
done

if [[ -z "$NOTE_ID" ]]; then
    echo "Error: Note ID is required"
    echo "Use --help for usage information"
    exit 1
fi

ELISP_EXPR="(progn
  (require 'ekg)
  (ekg-connect)
  (let ((note (ekg-get-note-with-id $NOTE_ID)))
    (if note
        (progn (ekg-note-trash note) (princ \"Trashed note $NOTE_ID\"))
      (princ \"Error: Note $NOTE_ID not found\"))))"

EMACSCLIENT_CMD=("${EMACSCLIENT:-emacsclient}")
if [[ -n "$DAEMON_NAME" ]]; then
    EMACSCLIENT_CMD+=("-s" "$DAEMON_NAME")
fi

if ! OUTPUT=$("${EMACSCLIENT_CMD[@]}" --eval "$ELISP_EXPR" 2>&1); then
    echo "Error: Failed to trash note. Is the Emacs daemon running?" >&2
    echo "$OUTPUT" >&2
    exit 1
fi

echo "$OUTPUT" | sed 's/^"//; s/"$//'
